### ISSUE TITLE
Need to restart Probe Service

### ISSUE THREAD

**Issue by grumpymojo** [andyzib/LetsEncrypt-PRTG#2]
I found when running this that the probe service misbehaved until I restarted it.
I suggest adding this to your script.

Restart-Service -Name PRTGProbeService - Force

**Comment by andyzib** [comment]
Interesting, I've not had any issue with this in over two years of Certify managing my cert and installing it using the script. I'm running an unlimited sensor licenses with multiple remote probes connecting in. Maybe I'll add the option to restart the ProbeService as a switch parameter.

**Comment by grumpymojo** [comment]
Maybe it's something in our environment. I suppose it won't hurt to have a switch for those that need it.
I appreciate the response.
